### PR TITLE
Attempt to fix mod folder not opening on osx

### PR DESCRIPTION
**Pull request by Kroporo**
This is an untested change!

### CODE REVIEW

**Comment by autious** [comment]
I should probably test it on my Mac before merging then, is it verified working on windows?

**Comment by autious** [comment]
Did you look up any particular resource for this fix or is it a swing in the dark?

**Comment by Kroporo** [comment]
It is tested on windows, but for linux and osx this is sort of a swing in the dark.
Did read up on a few issues people had, malformed links and links with spaces came up quite often.

The Unity documentation states that you can not open files via Application.OpenURL due to security concerns, it is unclear if this includes folders, but it might.

**Comment by Kroporo** [comment]
It appears that this did not fix the issue.

However, I don't think this pull request needs to be reverted, as it does some cleanup regardless

**Pull request merged**
